create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  description text not null,
  email varchar(320),
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

create policy "feedback_insert_anon" on public.feedback
for insert
to anon
with check (true);

create policy "feedback_insert_authenticated" on public.feedback
for insert
to authenticated
with check (true);

grant insert on public.feedback to anon;
grant insert on public.feedback to authenticated;

